package com.sf.dbswitch.core.db.ormlite;

import com.j256.ormlite.field.DatabaseField;
import java.text.SimpleDateFormat;
import java.util.Date;
import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

/**
 * A simple demonstration object we are creating and persisting to the database.
 */
@Entity
public class SimpleData {

	// id is generated by the database and set on the object automagically
	@Id(autoincrement = true)
	@DatabaseField(generatedId = true)
	Long id;
	@DatabaseField(index = true)
	String string;
	@DatabaseField
	Long millis;
	@DatabaseField
	Date date;
	@DatabaseField
	Boolean even;

	SimpleData() {
		// needed by ormlite
	}

	public SimpleData(long millis) {
		this.date = new Date(millis);
		this.string = (millis % 1000) + "ms";
		this.millis = millis;
		this.even = ((millis % 2) == 0);
	}
	@Generated(hash = 2086564753)
	public SimpleData(Long id, String string, Long millis, Date date,
			Boolean even) {
		this.id = id;
		this.string = string;
		this.millis = millis;
		this.date = date;
		this.even = even;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id=").append(id);
		sb.append(", ").append("string=").append(string);
		sb.append(", ").append("millis=").append(millis);
		SimpleDateFormat dateFormatter = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss.S");
		sb.append(", ").append("date=").append(dateFormatter.format(date));
		sb.append(", ").append("even=").append(even);
		return sb.toString();
	}

	public Long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getString() {
		return this.string;
	}

	public void setString(String string) {
		this.string = string;
	}

	public Long getMillis() {
		return this.millis;
	}

	public void setMillis(long millis) {
		this.millis = millis;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Boolean getEven() {
		return this.even;
	}

	public void setEven(boolean even) {
		this.even = even;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public void setMillis(Long millis) {
		this.millis = millis;
	}

	public void setEven(Boolean even) {
		this.even = even;
	}
}
